/****************************************************************************************
* Project        : Silicon Sprint Hackathon 2026
* Problem        : Power-Aware 16-bit Multiplier Design
*
* Event          : Silicon Sprint Hackathon
* Organized by   : Mindgrove Technologies
* In collaboration with : SRM Institute of Science and Technology
* Date           : March 10–11, 2026
*
* Team           : Silicon Sprint - Team 31
*
* Module Name    : partial_product_gen
*
* Module Function :
* This module generates the signed partial product required for the
* Radix-4 Booth multiplication algorithm.
*
* Based on the control signals generated by the Booth encoder:
*
*   zero → Partial product = 0
*   one  → Partial product = X
*   two  → Partial product = 2X
*   neg  → Negates the generated partial product
*
* The multiplicand is sign-extended before generating the partial product
* to correctly support signed multiplication.
*
* Operation Summary :
*
*   zero = 1 → PP = 0
*   one  = 1 → PP =  X
*   two  = 1 → PP = 2X
*   neg  = 1 → PP = -PP
*
* The output PP is then shifted and accumulated with other partial
* products to produce the final multiplier result.
*
* Language       : SystemVerilog
* Target Tech    : 90 nm Standard Cell Library
****************************************************************************************/

module partial_product_gen #(
    parameter N = 16
)(
    input  logic [N-1:0] X,
    input  logic zero,
    input  logic neg,
    input  logic one,
    input  logic two,

    output logic signed [N:0] PP
);

logic signed [N:0] X_ext;
logic signed [N:0] result;

assign X_ext = {X[N-1], X};

always_comb begin

    if (zero)
        result = 0;

    else if (one)
        result = X_ext;

    else if (two)
        result = X_ext <<< 1;

    else
        result = 0;

    if (neg)
        PP = -result;
    else
        PP = result;

end

endmodule
